version: "3.8"

services:
  db:
    image: postgres:16
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: casdoor
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: casdoor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casdoor"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  casdoor:
    # Dùng image chính thức (khuyến nghị), hoặc bỏ dòng image và giữ build: .
    image: casbin/casdoor:latest
    # build: .   # <- bỏ comment nếu bạn muốn build từ Dockerfile local
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: "true"

      # Casdoor đọc key 'driverName' / 'dataSourceName' trong app.conf.
      # Để chắc ăn, set cả lowercase & UPPERCASE.
      driverName: "postgres"
      dataSourceName: "user=casdoor password=change_me host=db port=5432 dbname=casdoor sslmode=disable"
      DRIVER_NAME: "postgres"
      DATA_SOURCE_NAME: "user=casdoor password=change_me host=db port=5432 dbname=casdoor sslmode=disable"
    ports:
      - "8000:8000"
    volumes:
      - ./conf:/conf # app.conf, init_data.json...
      - ./web/build:/web/build # FE build (nếu dùng)
      - ./uploads:/files # ✅ Storage LocalFS → set Path prefix = /files/uploads trong Provider
      - casdoor_logs:/app/logs # (tùy chọn) lưu log

volumes:
  pg_data:
  casdoor_logs:
