version: "3.8"
services:
  db:
    image: mysql:8.0.33
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: casdoor
      MYSQL_USER: casdoor
      MYSQL_PASSWORD: change_me
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p123456"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # <<<< Dùng named volume, KHÔNG bind ./data/mysql

  casdoor:
    image: casbin/casdoor:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    entrypoint: /bin/sh -c './server --createDatabase=true'
    environment:
      RUNNING_IN_DOCKER: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./conf:/conf

volumes:
  db_data:
